### ISSUE TITLE
New api not working for some people

### ISSUE THREAD

**Issue by MontakOleg** [AntonShevchuk/wme-bootstrap#1]
Hi Anton, thanks for great scripts!

Seems like after migrating to new userscript API (ef02bf0b72b20ae7d76ac272b1fd5fa31fd5bb43) it stopped working for some people (including me). `wme-logged-in` / `wme-ready` is never triggered.

See for example last messages in this thread:
https://www.waze.com/forum/viewtopic.php?t=87931&start=200

Last update (0d3e549faa49bc756f9f8a6e92ae1739e02f4cad) also did not fix the problem.

Old version (https://greasyfork.org/en/scripts/450160-wme-bootstrap?version=1126584) works fine.

May this new API not be available in some regions / for some users?

**Comment by AntonShevchuk** [comment]
Hi
Can you check new version with new version of the WME?

**Comment by MontakOleg** [comment]
It works 🎉
Thank you, I think we can close issue
